# -*- coding: utf-8 -*-
"""desafio banco.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14vfOyknh4i-CVclfGnUNLtcGzAP4rwnz
"""

import datetime

menu = '''
[d] depositar
[s] sacar
[e] extrato
[q] sair
=>'''

saldo = 800
limite = 500
extrato = []
numero_saques = 0 
LIMITE_SAQUES = 3

while True:

  opcao = input(menu)

  if opcao == 'd':
    valor_deposito = float(input('Qual valor você quer depositar?'))
    
    if valor_deposito > 0:
      now = datetime.datetime.now()
      str_now = now.strftime("%d/%m/%Y %H:%M:%S")
      saldo += valor_deposito
      print(f'Seu saldo agora é de R$ {saldo}')
      extrato.append(f'{str_now} Deposito de R$ {valor_deposito}')
    
    else:
      print('Não é possivel depositar valores menores que R$ 0.00')

  

  elif opcao == 's':
    
    if numero_saques < LIMITE_SAQUES:
      valor_saque = float(input('Qual valor você quer sacar?'))
     
      if valor_saque <= limite:

        if valor_saque >0:
       
            if valor_saque <= saldo:
              now = datetime.datetime.now()
              str_now = now.strftime("%d/%m/%Y %H:%M:%S")
              saldo -= valor_saque
              numero_saques += 1
              extrato.append(f'{str_now} Saque de R$ {valor_saque}')
              print(f'Saque efetuado com sucesso, seu saldo agora é de R$ {saldo}')
            
            else:
              print('Saldo insuficiente')
     
        else:
          print('O valor minimo para saque é de R$ 0.01')

      else:
        print(f'Você só pode sacar até R$ {limite}')

    else:
      print('Limite de saques diarios atingidos')  

  


  elif opcao == 'e':
      for item in extrato:
        print(item)


  elif opcao == 'q':
    print('Volte sempre')
    break